@ECHO OFF
setlocal
SET DebugBuild="build\net-3.5\debug"
SET CastlePrj="%Develop%\IoC\CastleProject"
SET CastleCore="%CastlePrj%\Core\%DebugBuild%"
SET CastleIoC="%CastlePrj%\InversionOfControl\%DebugBuild%"
SET CastleDP="%CastlePrj%\DynamicProxy\%DebugBuild%"
SET CastleAR="%CastlePrj%\ActiveRecord\%DebugBuild%"
SET CastleARI="%CastlePrj%\ActiveRecordIntegration\%DebugBuild%"
SET CastleDA="%CastlePrj%\DictionaryAdapter\%DebugBuild%"
SET CastleBind="%CastlePrj%\Binder\%DebugBuild%"
SET CastleEmail="%CastlePrj%\EmailSender\%DebugBuild%"
SET CastlePage="%CastlePrj%\Pagination\%DebugBuild%"
SET CastleSched="%CastlePrj%\Scheduler\%DebugBuild%"
SET CastleTemp="%CastlePrj%\TemplateEngine\%DebugBuild%"
SET CastleVal="%CastlePrj%\Validator\%DebugBuild%"
SET CastleATM="%CastlePrj%\AutomaticTransactionManagement\%DebugBuild%"
SET CastleTX="%CastlePrj%\TransactionService\%DebugBuild%"
SET CastleNHI="%CastlePrj%\NHibernateIntegration\
SET CastleWCF="%CastlePrj%\Wcf\%DebugBuild%"
SET CastleNV="%CastlePrj%\NVelocity\%DebugBuild%"
SET CastleSync="%CastlePrj%\Synchronize\%DebugBuild%"
SET CastleMono="%CastlePrj%\Monorail\%DebugBuild%"
SET CastleContrib="%Develop%\IoC\CastleProject\CastleContrib"

copy %CastleCore%\Castle.Core.dll "%~dp0"
copy %CastleCore%\Castle.Core.pdb "%~dp0"
copy %CastleBind%\Castle.Components.Binder.dll "%~dp0"
copy %CastleBind%\Castle.Components.Binder.pdb "%~dp0"
copy %CastleVal%\Castle.Components.Validator.dll "%~dp0"
copy %CastleVal%\Castle.Components.Validator.pdb "%~dp0"
copy %CastleDA%\Castle.Components.DictionaryAdapter.dll "%~dp0"
copy %CastleDA%\Castle.Components.DictionaryAdapter.pdb "%~dp0"
copy %CastleSched%\Castle.Components.Scheduler.dll "%~dp0"
copy %CastleSched%\Castle.Components.Scheduler.pdb "%~dp0"
copy %CastleSched%\Castle.Components.Scheduler.WindsorExtension.dll "%~dp0"
copy %CastleSched%\Castle.Components.Scheduler.WindsorExtension.pdb "%~dp0"
copy %CastleEmail%\Castle.Components.Common.EmailSender.dll "%~dp0"
copy %CastleEmail%\Castle.Components.Common.EmailSender.pdb "%~dp0"
copy %CastleTemp%\Castle.Components.Common.TemplateEngine.dll "%~dp0"
copy %CastleTemp%\Castle.Components.Common.TemplateEngine.pdb "%~dp0"
copy %CastleTemp%\Castle.Components.Common.TemplateEngine.NVelocityTemplateEngine.dll "%~dp0"
copy %CastleTemp%\Castle.Components.Common.TemplateEngine.NVelocityTemplateEngine.pdb "%~dp0"
copy %CastleDP%\Castle.DynamicProxy2.dll "%~dp0"
copy %CastleDP%\Castle.DynamicProxy2.pdb "%~dp0"
copy %CastleSync%\Castle.Facilities.Synchronize.dll "%~dp0"
copy %CastleSync%\Castle.Facilities.Synchronize.pdb "%~dp0"
copy %CastleATM%\Castle.Facilities.AutomaticTransactionManagement.dll "%~dp0"
copy %CastleATM%\Castle.Facilities.AutomaticTransactionManagement.pdb "%~dp0"
copy %CastleIoC%\Castle.MicroKernel.dll "%~dp0"
copy %CastleIoC%\Castle.MicroKernel.pdb "%~dp0"
copy %CastleIoC%\Castle.Windsor.dll "%~dp0"
copy %CastleIoC%\Castle.Windsor.pdb "%~dp0"
copy %CastleIoC%\Castle.Facilities.Logging.dll "%~dp0"
copy %CastleIoC%\Castle.Facilities.Logging.pdb "%~dp0"
copy %CastleCore%\Castle.Services.Logging.Log4netIntegration.dll "%~dp0"
copy %CastleCore%\Castle.Services.Logging.Log4netIntegration.pdb "%~dp0"
copy %CastleTX%\Castle.Services.Transaction.dll "%~dp0"
copy %CastleTX%\Castle.Services.Transaction.pdb "%~dp0"
copy %CastleAR%\Castle.ActiveRecord.dll "%~dp0"
copy %CastleAR%\Castle.ActiveRecord.pdb "%~dp0"
copy %CastleAR%\Castle.ActiveRecord.Linq.dll "%~dp0"
copy %CastleAR%\Castle.ActiveRecord.Linq.pdb "%~dp0"
copy %CastleARI%\Castle.Facilities.ActiveRecordIntegration.dll "%~dp0"
copy %CastleARI%\Castle.Facilities.ActiveRecordIntegration.pdb "%~dp0"
copy %CastleWCF%\Castle.Facilities.WcfIntegration.dll "%~dp0"
copy %CastleWCF%\Castle.Facilities.WcfIntegration.pdb "%~dp0"
copy %CastleMono%\Castle.MonoRail.Framework.dll "%~dp0"
copy %CastleMono%\Castle.MonoRail.Framework.pdb "%~dp0"
copy %CastleMono%\Castle.MonoRail.ActiveRecordSupport.dll "%~dp0"
copy %CastleMono%\Castle.MonoRail.ActiveRecordSupport.pdb "%~dp0"
copy %CastleMono%\Newtonsoft.Json.dll "%~dp0"
copy %CastleNV%\NVelocity.dll "%~dp0"
